version: '3'

networks:
  default-network:
    driver: bridge

services:
  web:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis
    networks:
      - default-network
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default-network
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - default-network
